# Generated by Django 5.2 on 2025-05-02 09:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solosync_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='soloroutine',
            name='difficulty',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 - Very Easy'), (2, '2 - Easy'), (3, '3 - Medium'), (4, '4 - Hard'), (5, '5 - Very Hard')], help_text="Coach's rating of the routine difficulty (1-5)", null=True),
        ),
        migrations.AlterField(
            model_name='routinedrilllink',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=60, help_text='Time for this specific drill step (seconds).', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='routinedrilllink',
            name='routine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routinedrilllink_set', to='solosync_api.soloroutine'),
        ),
        migrations.AlterField(
            model_name='solodrill',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_solo_drills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='soloroutine',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_solo_routines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solosessionlog',
            name='completed_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Timestamp when the session log was submitted'),
        ),
        migrations.AlterField(
            model_name='solosessionlog',
            name='physical_difficulty',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Player rating (1-5) of physical difficulty', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='solosessionmetric',
            name='drill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logged_metric_instances', to='solosync_api.solodrill'),
        ),
    ]
