# Generated by Django 5.2 on 2025-05-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solosync_api', '0002_soloroutine_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solodrill',
            name='youtube_link',
            field=models.URLField(blank=True, help_text='Optional YouTube link for drill explanation/demonstration.', max_length=255, null=True),
        ),
    ]
