# Generated by Django 5.2 on 2025-05-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solosync_api', '0003_solodrill_youtube_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoloDrillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Racketwork, Fitness, Stretching & Warmup, Ghosting, Pressure Drills', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the category.', null=True)),
            ],
            options={
                'verbose_name': 'Solo Drill Category',
                'verbose_name_plural': 'Solo Drill Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='solodrill',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='solodrill',
            name='metrics_definition',
        ),
        migrations.AddField(
            model_name='solodrill',
            name='default_duration_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Suggested default duration for this drill in seconds, if applicable (e.g., for timed drills).', null=True),
        ),
        migrations.AddField(
            model_name='solodrill',
            name='metric_type',
            field=models.CharField(blank=True, choices=[('AMOUNT', 'Amount (e.g., count, repetitions)'), ('TIME', 'Time to Complete (e.g., duration for a set task)')], help_text='The type of metric collected for this drill, if any.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='solodrill',
            name='participant_type',
            field=models.CharField(choices=[('SOLO', 'Solo (Player Only)'), ('COACH_PLAYER', 'Coach + Player(s)'), ('ANY', 'Any (Flexible)')], default='SOLO', help_text='Intended participant setup for this drill when used in a routine.', max_length=20),
        ),
        migrations.AlterField(
            model_name='solodrill',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solodrill',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Categories this drill belongs to (e.g., Fitness, Ghosting).', related_name='solo_drills', to='solosync_api.solodrillcategory'),
        ),
    ]
