# Generated by Django 5.2 on 2025-05-13 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solosync_api', '0004_solodrillcategory_alter_solodrill_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routinedrilllink',
            name='metrics_to_collect',
        ),
    ]
