# Generated by Django 5.2 on 2025-04-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the drill.', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of how to perform the drill, its objectives, etc.')),
                ('category', models.CharField(choices=[('TECH', 'Technique'), ('FOOT', 'Footwork'), ('COND', 'Condition Game'), ('FIT', 'Fitness'), ('TACT', 'Tactics'), ('MENT', 'Mental Skill'), ('SERV', 'Serve/Return'), ('OTHR', 'Other')], help_text='The primary category this drill falls into.', max_length=4)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Suggested duration for the drill in minutes (optional).', null=True)),
            ],
        ),
    ]
