# Generated by Django 5.2 on 2025-04-17 05:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.TimeField()),
                ('planned_duration_minutes', models.PositiveIntegerField(default=90, help_text='Total planned duration of the session in minutes.')),
                ('notes', models.TextField(blank=True, help_text='Overall notes or objectives for the session.')),
                ('coaches_attending', models.ManyToManyField(blank=True, help_text='Select coaches who might be present for this session.', related_name='sessions_attending', to='planning.coach')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TimeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_offset_minutes', models.PositiveIntegerField(default=0, help_text='Start time of this block in minutes from the session start.')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration of this specific time block in minutes.')),
                ('number_of_courts', models.PositiveIntegerField(default=1, help_text='Number of courts available during this block.')),
                ('block_focus', models.CharField(blank=True, help_text='Optional short description of the focus for this time block.', max_length=255)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_blocks', to='planning.session')),
            ],
            options={
                'ordering': ['session', 'start_offset_minutes'],
            },
        ),
        migrations.CreateModel(
            name='ActivityAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_number', models.PositiveIntegerField(help_text='Which court this activity takes place on (e.g., 1, 2, 3).')),
                ('custom_activity_name', models.CharField(blank=True, help_text="Use if not selecting a Drill from the library (e.g., 'Warm-up', 'Water Break').", max_length=200)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration allocated for this specific activity on this court.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of activity on this court within this time block (0 comes first).')),
                ('drill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planning.drill')),
                ('lead_coach', models.ForeignKey(blank=True, help_text='Coach leading this specific activity.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='planning.coach')),
                ('time_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='planning.timeblock')),
            ],
            options={
                'ordering': ['time_block', 'court_number', 'order'],
            },
        ),
    ]
