# Generated by Django 5.2 on 2025-04-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_coach_session_timeblock_activityassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('skill_level', models.CharField(choices=[('BEG', 'Beginner'), ('INT', 'Intermediate'), ('ADV', 'Advanced')], default='INT', help_text="Player's approximate skill level.", max_length=3)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck if player is no longer active.')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-date', '-start_time']},
        ),
        migrations.AddField(
            model_name='session',
            name='attendees',
            field=models.ManyToManyField(blank=True, help_text='Players marked as attending this session.', related_name='sessions_attended', to='planning.player'),
        ),
    ]
