# Generated by Django 5.2 on 2025-04-18 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_player_alter_session_options_session_attendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityassignment',
            name='court_number',
            field=models.PositiveIntegerField(help_text='Which court (e.g., 1, 2).'),
        ),
        migrations.AlterField(
            model_name='activityassignment',
            name='custom_activity_name',
            field=models.CharField(blank=True, help_text='Use if not selecting a Drill.', max_length=200),
        ),
        migrations.AlterField(
            model_name='activityassignment',
            name='duration_minutes',
            field=models.PositiveIntegerField(help_text='Duration for this activity.'),
        ),
        migrations.AlterField(
            model_name='activityassignment',
            name='lead_coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planning.coach'),
        ),
        migrations.AlterField(
            model_name='activityassignment',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order on court within block.'),
        ),
        migrations.AlterField(
            model_name='drill',
            name='category',
            field=models.CharField(choices=[('TECH', 'Technique'), ('FOOT', 'Footwork'), ('COND', 'Condition Game'), ('FIT', 'Fitness'), ('TACT', 'Tactics'), ('MENT', 'Mental Skill'), ('SERV', 'Serve/Return'), ('OTHR', 'Other')], help_text='Primary category.', max_length=4),
        ),
        migrations.AlterField(
            model_name='drill',
            name='description',
            field=models.TextField(help_text='Detailed description...'),
        ),
        migrations.AlterField(
            model_name='drill',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Suggested duration (optional).', null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='skill_level',
            field=models.CharField(choices=[('BEG', 'Beginner'), ('INT', 'Intermediate'), ('ADV', 'Advanced')], default='INT', help_text='Approximate skill level.', max_length=3),
        ),
        migrations.AlterField(
            model_name='session',
            name='coaches_attending',
            field=models.ManyToManyField(blank=True, related_name='sessions_attending', to='planning.coach'),
        ),
        migrations.AlterField(
            model_name='session',
            name='notes',
            field=models.TextField(blank=True, help_text='Overall notes/objectives.'),
        ),
        migrations.AlterField(
            model_name='session',
            name='planned_duration_minutes',
            field=models.PositiveIntegerField(default=90, help_text='Total planned duration.'),
        ),
        migrations.AlterField(
            model_name='timeblock',
            name='block_focus',
            field=models.CharField(blank=True, help_text='Optional focus.', max_length=255),
        ),
        migrations.AlterField(
            model_name='timeblock',
            name='duration_minutes',
            field=models.PositiveIntegerField(help_text='Duration of this block.'),
        ),
        migrations.AlterField(
            model_name='timeblock',
            name='number_of_courts',
            field=models.PositiveIntegerField(default=1, help_text='Courts available.'),
        ),
        migrations.AlterField(
            model_name='timeblock',
            name='start_offset_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Start offset from session start.'),
        ),
        migrations.CreateModel(
            name='SchoolGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the school group (e.g., Zwartkop A, Waterkloof Boys U16)', max_length=150, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the group.')),
                ('players', models.ManyToManyField(blank=True, help_text='Players belonging to this group.', related_name='school_groups', to='planning.player')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='session',
            name='school_group',
            field=models.ForeignKey(help_text='The specific school group this session is for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='planning.schoolgroup'),
        ),
    ]
