# Generated by Django 5.2 on 2025-04-18 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_alter_activityassignment_court_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeblock',
            name='rotation_interval_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Rotate player groups between courts every X minutes within this block. Leave blank/0 for no rotation.', null=True),
        ),
        migrations.AlterField(
            model_name='schoolgroup',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description.'),
        ),
        migrations.AlterField(
            model_name='schoolgroup',
            name='name',
            field=models.CharField(help_text='Name of the school group', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='schoolgroup',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='school_groups', to='planning.player'),
        ),
        migrations.AlterField(
            model_name='session',
            name='attendees',
            field=models.ManyToManyField(blank=True, help_text='Players marked as attending.', related_name='sessions_attended', to='planning.player'),
        ),
        migrations.AlterField(
            model_name='session',
            name='school_group',
            field=models.ForeignKey(help_text='The group this session is for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='planning.schoolgroup'),
        ),
    ]
