# Generated by Django 5.2 on 2025-04-23 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0006_player_photo_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activityassignment",
            options={
                "ordering": ["time_block", "court_number", "order"],
                "verbose_name_plural": "Session Planning | Activity Assignments",
            },
        ),
        migrations.AlterModelOptions(
            name="backwalldriverecord",
            options={
                "ordering": ["player", "-date_recorded", "shot_type"],
                "verbose_name_plural": "Player Records | Backwall Drives",
            },
        ),
        migrations.AlterModelOptions(
            name="coach",
            options={"verbose_name_plural": "Session Planning | Coaches"},
        ),
        migrations.AlterModelOptions(
            name="courtsprintrecord",
            options={
                "ordering": ["player", "-date_recorded", "duration_choice"],
                "verbose_name_plural": "Player Records | Court Sprints",
            },
        ),
        migrations.AlterModelOptions(
            name="drill",
            options={"verbose_name_plural": "Session Planning | Drills"},
        ),
        migrations.AlterModelOptions(
            name="matchresult",
            options={
                "ordering": ["player", "-date"],
                "verbose_name_plural": "Player Records | Match Results",
            },
        ),
        migrations.AlterModelOptions(
            name="player",
            options={
                "ordering": ["last_name", "first_name"],
                "verbose_name_plural": "Player Profiles | Players",
            },
        ),
        migrations.AlterModelOptions(
            name="schoolgroup",
            options={
                "ordering": ["name"],
                "verbose_name_plural": "Player Profiles | School Groups",
            },
        ),
        migrations.AlterModelOptions(
            name="session",
            options={
                "ordering": ["-date", "-start_time"],
                "verbose_name_plural": "Session Planning | Sessions",
            },
        ),
        migrations.AlterModelOptions(
            name="sessionassessment",
            options={
                "ordering": ["-date_recorded", "player"],
                "verbose_name_plural": "Player Records | Session Assessments",
            },
        ),
        migrations.AlterModelOptions(
            name="volleyrecord",
            options={
                "ordering": ["player", "-date_recorded", "shot_type"],
                "verbose_name_plural": "Player Records | Volleys",
            },
        ),
        migrations.AlterField(
            model_name="courtsprintrecord",
            name="score",
            field=models.IntegerField(
                help_text="Score achieved (e.g., number of laps completed)."
            ),
        ),
        migrations.AlterField(
            model_name="matchresult",
            name="is_competitive",
            field=models.BooleanField(
                default=False, help_text="Check if official competitive match."
            ),
        ),
        migrations.AlterField(
            model_name="matchresult",
            name="match_notes",
            field=models.TextField(blank=True, help_text="Coach observations, etc."),
        ),
        migrations.AlterField(
            model_name="matchresult",
            name="player_score_str",
            field=models.CharField(
                help_text="Score details (e.g., 3-1, or 11-8, 11-9...)", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="matchresult",
            name="session",
            field=models.ForeignKey(
                blank=True,
                help_text="Link if practice match.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="practice_matches",
                to="planning.session",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Optional profile photo.",
                null=True,
                upload_to="player_photos/",
            ),
        ),
        migrations.AlterField(
            model_name="sessionassessment",
            name="coach_notes",
            field=models.TextField(blank=True, help_text="Specific observations."),
        ),
        migrations.AlterField(
            model_name="sessionassessment",
            name="composure_rating",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "1 Star"),
                    (2, "2 Stars"),
                    (3, "3 Stars"),
                    (4, "4 Stars"),
                    (5, "5 Stars"),
                ],
                help_text="Composure rating (1-5).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sessionassessment",
            name="decision_making_rating",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "1 Star"),
                    (2, "2 Stars"),
                    (3, "3 Stars"),
                    (4, "4 Stars"),
                    (5, "5 Stars"),
                ],
                help_text="Decision making rating (1-5).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sessionassessment",
            name="effort_rating",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "1 Star"),
                    (2, "2 Stars"),
                    (3, "3 Stars"),
                    (4, "4 Stars"),
                    (5, "5 Stars"),
                ],
                help_text="Effort/motivation rating (1-5).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sessionassessment",
            name="focus_rating",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "1 Star"),
                    (2, "2 Stars"),
                    (3, "3 Stars"),
                    (4, "4 Stars"),
                    (5, "5 Stars"),
                ],
                help_text="Focus rating (1-5).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sessionassessment",
            name="resilience_rating",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "1 Star"),
                    (2, "2 Stars"),
                    (3, "3 Stars"),
                    (4, "4 Stars"),
                    (5, "5 Stars"),
                ],
                help_text="Resilience rating (1-5).",
                null=True,
            ),
        ),
    ]
