# Generated by Django 5.2 on 2025-04-22 07:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0007_alter_backwalldriverecord_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualCourtAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_assignments', to='planning.player')),
                ('time_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_assignments', to='planning.timeblock')),
            ],
            options={
                'ordering': ['time_block', 'court_number', 'player__last_name'],
                'unique_together': {('time_block', 'player')},
            },
        ),
    ]
