# Generated by Django 5.2 on 2025-04-23 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0007_alter_activityassignment_options_and_more"),
        ("planning", "0008_manualcourtassignment"),
    ]

    operations = []
