# Generated by Django 5.2 on 2025-04-24 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0010_alter_activityassignment_options_and_more'),
    ]

    operations = [
    ]
