# Generated by Django 5.2 on 2025-04-26 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0011_sync_pa_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activityassignment",
            options={"ordering": ["time_block", "court_number", "order"]},
        ),
        migrations.AlterModelOptions(
            name="backwalldriverecord",
            options={"ordering": ["-date_recorded", "shot_type"]},
        ),
        migrations.AlterModelOptions(
            name="coach",
            options={},
        ),
        migrations.AlterModelOptions(
            name="courtsprintrecord",
            options={"ordering": ["-date_recorded", "duration_choice"]},
        ),
        migrations.AlterModelOptions(
            name="drill",
            options={},
        ),
        migrations.AlterModelOptions(
            name="matchresult",
            options={"ordering": ["-date", "player__last_name"]},
        ),
        migrations.AlterModelOptions(
            name="player",
            options={"ordering": ["last_name", "first_name"]},
        ),
        migrations.AlterModelOptions(
            name="schoolgroup",
            options={},
        ),
        migrations.AlterModelOptions(
            name="session",
            options={"ordering": ["-date", "-start_time"]},
        ),
        migrations.AlterModelOptions(
            name="sessionassessment",
            options={"ordering": ["-date_recorded", "player__last_name"]},
        ),
        migrations.AlterModelOptions(
            name="volleyrecord",
            options={"ordering": ["-date_recorded", "shot_type"]},
        ),
        migrations.AlterField(
            model_name="courtsprintrecord",
            name="score",
            field=models.PositiveIntegerField(
                help_text="Number of full court lengths completed."
            ),
        ),
        migrations.AlterField(
            model_name="matchresult",
            name="is_competitive",
            field=models.BooleanField(
                default=False, help_text="Was this an official league/tournament match?"
            ),
        ),
        migrations.AlterField(
            model_name="matchresult",
            name="match_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="matchresult",
            name="player_score_str",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="matchresult",
            name="session",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: Link to the session if it was a practice match during training.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matches_played",
                to="planning.session",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="player_photos/"),
        ),
        migrations.AlterField(
            model_name="sessionassessment",
            name="coach_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="sessionassessment",
            name="composure_rating",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Poor"),
                    (2, "Below Average"),
                    (3, "Average"),
                    (4, "Good"),
                    (5, "Excellent"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sessionassessment",
            name="decision_making_rating",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Poor"),
                    (2, "Below Average"),
                    (3, "Average"),
                    (4, "Good"),
                    (5, "Excellent"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sessionassessment",
            name="effort_rating",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Poor"),
                    (2, "Below Average"),
                    (3, "Average"),
                    (4, "Good"),
                    (5, "Excellent"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sessionassessment",
            name="focus_rating",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Poor"),
                    (2, "Below Average"),
                    (3, "Average"),
                    (4, "Good"),
                    (5, "Excellent"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sessionassessment",
            name="resilience_rating",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Poor"),
                    (2, "Below Average"),
                    (3, "Average"),
                    (4, "Good"),
                    (5, "Excellent"),
                ],
                null=True,
            ),
        ),
    ]
