# Generated by Django 5.2 on 2025-04-26 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0012_alter_activityassignment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('strengths_observed', models.TextField(blank=True, verbose_name='Strengths Observed')),
                ('areas_for_development', models.TextField(blank=True, verbose_name='Areas for Development')),
                ('suggested_focus', models.TextField(blank=True, verbose_name='Suggested Focus/Next Steps')),
                ('general_notes', models.TextField(blank=True, verbose_name='General Notes')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='planning.player')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_entries', to='planning.session')),
            ],
            options={
                'verbose_name': 'Coach Feedback',
                'verbose_name_plural': 'Coach Feedback Entries',
                'ordering': ['-date_recorded'],
            },
        ),
        migrations.CreateModel(
            name='CoachJournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('entry_text', models.TextField(verbose_name='Journal Entry')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='planning.player')),
            ],
            options={
                'verbose_name': 'Coach Journal Entry',
                'verbose_name_plural': 'Coach Journal Entries',
                'ordering': ['-date_recorded'],
            },
        ),
    ]
