# Generated by Django 5.2 on 2025-04-26 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0013_coachfeedback_coachjournalentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoachJournalEntry',
        ),
    ]
