# Generated by Django 5.2 on 2025-04-27 12:19

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0015_schoolgroup_attendance_form_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-session_date', '-session_start_time']},
        ),
        migrations.RenameField(
            model_name='session',
            old_name='date',
            new_name='session_date',
        ),
        migrations.RemoveField(
            model_name='session',
            name='start_time',
        ),
        migrations.AddField(
            model_name='session',
            name='session_start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='session',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='attended_sessions', to='planning.player'),
        ),
        migrations.AlterField(
            model_name='session',
            name='coaches_attending',
            field=models.ManyToManyField(blank=True, related_name='coached_sessions', to='planning.coach'),
        ),
        migrations.AlterField(
            model_name='session',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional objectives or notes for the session.'),
        ),
        migrations.AlterField(
            model_name='session',
            name='planned_duration_minutes',
            field=models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
