# Generated by Django 5.2 on 2025-04-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0016_alter_session_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='assessments_complete',
            field=models.BooleanField(default=False, help_text='Mark as true once all player assessments for this session are done.'),
        ),
    ]
