# Generated by Django 5.2 on 2025-04-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0017_session_assessments_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Enter number including country code if outside SA (e.g., +44... or 082...)', max_length=20, verbose_name='Player Contact Number'),
        ),
        migrations.AddField(
            model_name='player',
            name='parent_contact_number',
            field=models.CharField(blank=True, help_text='Enter number including country code if outside SA (e.g., +44... or 082...)', max_length=20, verbose_name='Parent Contact Number'),
        ),
    ]
