# Generated by Django 5.2 on 2025-05-07 09:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0018_player_contact_number_player_parent_contact_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'ordering': ['name'], 'verbose_name_plural': 'Coaches'},
        ),
        migrations.AlterModelOptions(
            name='drill',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='schoolgroup',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='coach',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='coachfeedback',
            name='date_recorded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='match_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='opponent_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='opponent_score_str',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolgroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CoachAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text="Optional notes from the coach regarding their availability for this session (e.g., 'Can do first half').")),
                ('timestamp', models.DateTimeField(auto_now=True, help_text='When this availability status was last updated.')),
                ('coach', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='session_availabilities', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_availabilities', to='planning.session')),
            ],
            options={
                'verbose_name': 'Coach Availability',
                'verbose_name_plural': 'Coach Availabilities',
                'ordering': ['session__session_date', 'session__session_start_time', 'coach__username'],
                'unique_together': {('coach', 'session')},
            },
        ),
    ]
