# Generated by Django 5.2 on 2025-05-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0022_sessionassessment_submitted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Coach's hourly rate for payment.", max_digits=6, null=True),
        ),
    ]
