# Generated by Django 5.2 on 2025-05-08 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0023_coach_hourly_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField(help_text='The month (1-12) of the payslip period.')),
                ('year', models.PositiveIntegerField(help_text='The year (e.g., 2025) of the payslip period.')),
                ('file', models.FileField(help_text='The generated PDF payslip file.', upload_to='payslips/%Y/%m/')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='The total amount payable on this payslip.', max_digits=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this payslip record was created (and PDF generated).')),
                ('coach', models.ForeignKey(help_text='The coach to whom this payslip belongs.', on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='planning.coach')),
                ('generated_by', models.ForeignKey(blank=True, help_text='The user who initiated the generation of this payslip (e.g., superuser).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_payslips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payslip',
                'verbose_name_plural': 'Payslips',
                'ordering': ['-year', '-month', 'coach__user__last_name', 'coach__user__first_name', 'coach__name'],
                'unique_together': {('coach', 'month', 'year')},
            },
        ),
    ]
