# Generated by Django 5.2 on 2025-05-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0024_payslip'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_cancelled',
            field=models.BooleanField(default=False, help_text='Mark as true if the session has been cancelled.'),
        ),
        migrations.AddField(
            model_name='session',
            name='venue_name',
            field=models.CharField(blank=True, help_text='Name of the venue where the session takes place.', max_length=100, null=True),
        ),
    ]
