# Generated by Django 5.2 on 2025-05-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0025_session_is_cancelled_session_venue_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionassessment',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='If true, this assessment is hidden from regular view (still visible to superusers).'),
        ),
    ]
