# Generated by Django 5.2 on 2025-05-23 07:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0027_sessionassessment_superuser_reviewed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sessionassessment',
            unique_together={('session', 'player', 'submitted_by')},
        ),
    ]
