# Generated by Django 5.2 on 2025-05-24 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0028_alter_sessionassessment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachavailability',
            name='last_action',
            field=models.CharField(blank=True, choices=[('CONFIRM', 'Confirmed'), ('DECLINE', 'Declined')], help_text='The last explicit action (Confirm/Decline) taken by the coach for this session.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='coachavailability',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, help_text="Timestamp of when 'is_available' or 'last_action' was last explicitly set by coach action.", null=True),
        ),
        migrations.AlterField(
            model_name='coachavailability',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, help_text='When this availability status was last saved.'),
        ),
    ]
