# Generated by Django 5.2 on 2025-05-24 03:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0029_coachavailability_last_action_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachavailability',
            name='last_action',
            field=models.CharField(blank=True, choices=[('CONFIRM', 'Confirmed'), ('DECLINE', 'Declined')], help_text='The last explicit action ...', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='coachavailability',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes ...'),
        ),
        migrations.AlterField(
            model_name='coachavailability',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of when ...', null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips_generated_for', to='planning.coach'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='generated_by',
            field=models.ForeignKey(blank=True, help_text='The user who initiated the generation of this payslip (e.g., superuser).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payslips_initiated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='session',
            name='assessments_complete',
            field=models.BooleanField(default=False, help_text='Legacy field: Mark as true once all player assessments for this session are done.'),
        ),
        migrations.AlterField(
            model_name='sessionassessment',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_assessments_by_player', to='planning.player'),
        ),
        migrations.CreateModel(
            name='ScheduledClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('default_duration_minutes', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)])),
                ('default_venue_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='If unchecked, new sessions will not be generated from this rule.')),
                ('notes_for_rule', models.TextField(blank=True, help_text='Internal notes about this recurring schedule rule.', null=True)),
                ('default_coaches', models.ManyToManyField(blank=True, related_name='default_scheduled_classes', to='planning.coach')),
                ('school_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_classes', to='planning.schoolgroup')),
            ],
            options={
                'verbose_name': 'Scheduled Class Rule',
                'verbose_name_plural': 'Scheduled Class Rules',
                'ordering': ['school_group__name', 'day_of_week', 'start_time'],
                'unique_together': {('school_group', 'day_of_week', 'start_time')},
            },
        ),
        migrations.AddField(
            model_name='session',
            name='generated_from_rule',
            field=models.ForeignKey(blank=True, help_text='Link to the recurring schedule rule that generated this session, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_sessions', to='planning.scheduledclass'),
        ),
    ]
