# Generated by Django 5.2 on 2025-05-24 03:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0030_alter_coachavailability_last_action_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the venue (e.g., Midstream College Main Courts, Uitsig Court 1).', max_length=150, unique=True)),
                ('address', models.TextField(blank=True, help_text='Optional: Full address of the venue.', null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional: Any notes about the venue (e.g., access instructions, number of courts).', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this venue currently in use?')),
            ],
            options={
                'verbose_name': 'Venue',
                'verbose_name_plural': 'Venues',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='scheduledclass',
            name='default_venue_name',
        ),
        migrations.RemoveField(
            model_name='session',
            name='venue_name',
        ),
        migrations.AlterField(
            model_name='activityassignment',
            name='activity_notes',
            field=models.TextField(blank=True, help_text='Specific notes...'),
        ),
        migrations.AlterField(
            model_name='activityassignment',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=10, help_text='Estimated duration...', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='activityassignment',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of activity...'),
        ),
        migrations.AlterField(
            model_name='backwalldriverecord',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Optional: Link to session...', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drive_tests_conducted', to='planning.session'),
        ),
        migrations.AlterField(
            model_name='courtsprintrecord',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Optional: Link to session...', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sprint_tests_conducted', to='planning.session'),
        ),
        migrations.AlterField(
            model_name='drill',
            name='duration_minutes_default',
            field=models.PositiveIntegerField(default=10, help_text='Default duration in minutes...', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='drill',
            name='ideal_num_players',
            field=models.IntegerField(blank=True, choices=[(1, '1 Player'), (2, '2 Players'), (3, '3 Players'), (4, '4+ Players')], help_text='Ideal number of players...', null=True),
        ),
        migrations.AlterField(
            model_name='drill',
            name='suitable_for_any',
            field=models.BooleanField(default=False, help_text='Check if this drill works well regardless...'),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Optional: Link to session...', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_played', to='planning.session'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='generated_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this payslip record was created...'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='generated_by',
            field=models.ForeignKey(blank=True, help_text='The user who initiated...', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payslips_initiated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='session',
            name='assessments_complete',
            field=models.BooleanField(default=False, help_text='Legacy field: Consider using CoachSessionCompletion instead.'),
        ),
        migrations.AlterField(
            model_name='session',
            name='generated_from_rule',
            field=models.ForeignKey(blank=True, help_text='Link to the recurring schedule rule...', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_sessions', to='planning.scheduledclass'),
        ),
        migrations.AlterField(
            model_name='sessionassessment',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='If true, this assessment is hidden...'),
        ),
        migrations.AlterField(
            model_name='sessionassessment',
            name='superuser_reviewed',
            field=models.BooleanField(db_index=True, default=False, help_text='Checked by superuser if they have reviewed...'),
        ),
        migrations.AlterField(
            model_name='timeblock',
            name='block_focus',
            field=models.CharField(blank=True, help_text='Specific focus for this time block...', max_length=200),
        ),
        migrations.AlterField(
            model_name='timeblock',
            name='rotation_interval_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Optional: Rotate players...', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='volleyrecord',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Optional: Link to session...', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volley_tests_conducted', to='planning.session'),
        ),
        migrations.AddField(
            model_name='scheduledclass',
            name='default_venue',
            field=models.ForeignKey(blank=True, help_text='Default venue for this recurring class.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='planning.venue'),
        ),
        migrations.AddField(
            model_name='session',
            name='venue',
            field=models.ForeignKey(blank=True, help_text='Venue where the session takes place.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='planning.venue'),
        ),
    ]
