# Generated by Django 5.2 on 2025-06-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0031_venue_remove_scheduledclass_default_venue_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='coach',
            name='whatsapp_opt_in',
            field=models.BooleanField(default=False, help_text='Has the coach opted-in to receive WhatsApp notifications?'),
        ),
        migrations.AddField(
            model_name='coach',
            name='whatsapp_phone_number',
            field=models.CharField(blank=True, help_text='WhatsApp enabled phone number in E.164 format (e.g., +14155238886).', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='grade',
            field=models.IntegerField(blank=True, choices=[(0, 'Grade R'), (1, 'Grade 1'), (2, 'Grade 2'), (3, 'Grade 3'), (4, 'Grade 4'), (5, 'Grade 5'), (6, 'Grade 6'), (7, 'Grade 7'), (8, 'Grade 8'), (9, 'Grade 9'), (10, 'Grade 10'), (11, 'Grade 11'), (12, 'Grade 12 (Matric)'), (99, 'Other / Not Applicable')], null=True, verbose_name='School Grade'),
        ),
    ]
