# Generated by Django 5.2 on 2025-06-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0033_alter_coachfeedback_options_alter_payslip_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupassessment',
            name='superuser_reviewed',
            field=models.BooleanField(db_index=True, default=False, help_text='Checked by superuser if they have reviewed this group assessment.'),
        ),
    ]
