# Generated by Django 5.2 on 2025-06-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0034_groupassessment_superuser_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='experience_notes',
            field=models.TextField(blank=True, help_text='Brief notes on coaching experience, specializations, etc.', null=True, verbose_name='Coaching Experience'),
        ),
        migrations.AddField(
            model_name='coach',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='coach_photos/', verbose_name='Profile Photo'),
        ),
        migrations.AddField(
            model_name='coach',
            name='qualification_ssa_level',
            field=models.CharField(blank=True, choices=[('NONE', 'None / Not Applicable'), ('L1', 'Level 1'), ('L2', 'Level 2'), ('L3', 'Level 3'), ('OTH', 'Other')], default='NONE', help_text='Squash South Africa coaching qualification level.', max_length=5, verbose_name='SSA Qualification Level'),
        ),
        migrations.AddField(
            model_name='coach',
            name='qualification_wsf_level',
            field=models.CharField(blank=True, choices=[('NONE', 'None / Not Applicable'), ('L1', 'Level 1'), ('L2', 'Level 2'), ('L3', 'Level 3'), ('OTH', 'Other')], default='NONE', help_text='World Squash Federation coaching qualification level.', max_length=5, verbose_name='WSF Qualification Level'),
        ),
    ]
