# Generated by Django 5.2 on 2025-06-05 05:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0035_coach_experience_notes_coach_profile_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the event (e.g., Midstream Social Saturday - June, St. Alban's Tournament U19).", max_length=200)),
                ('event_type', models.CharField(choices=[('SOCIAL', 'Social Event'), ('TOURNMT', 'Tournament Support'), ('SCHOOL', 'School Function'), ('CEREMONY', 'Capping/Awards Ceremony'), ('MEETING', 'Coach/Staff Meeting'), ('WORKSHOP', 'Workshop/Training'), ('OTHER', 'Other Event')], default='OTHER', max_length=10, verbose_name='Event Type')),
                ('event_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Event Date & Time')),
                ('description', models.TextField(blank=True, help_text='Optional: Further details about the event.', null=True)),
                ('attending_coaches', models.ManyToManyField(blank=True, related_name='attended_events', to='planning.coach', verbose_name='Attending Coaches')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-event_date', 'name'],
            },
        ),
    ]
