# Generated by Django 5.2 on 2025-06-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0036_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='drill',
            name='youtube_link',
            field=models.URLField(blank=True, help_text='Optional: A link to a YouTube video demonstrating the drill.', max_length=1024, null=True, verbose_name='YouTube Link'),
        ),
    ]
