# Generated by Django 5.2 on 2025-06-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0037_drill_youtube_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='receive_weekly_schedule_email',
            field=models.BooleanField(default=True, help_text='If checked, this coach will receive the weekly schedule summary email every Sunday.', verbose_name='Receive Weekly Schedule Email'),
        ),
    ]
