# solosync_api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views # Import views from the current app

# Create a router and register our viewsets with it.
router = DefaultRouter()
router.register(r'assigned-routines', views.AssignedRoutinesViewSet, basename='assigned-routine')
router.register(r'session-logs', views.SoloSessionLogViewSet, basename='session-log')

# The API URLs are now determined automatically by the router.
# 'basename' is used to name the URL patterns generated by the router.
urlpatterns = [
    path('', include(router.urls)),

    # You could add other non-router views here if needed
]